### ISSUE TITLE
Uncaught ReferenceError: addtocart is not defined 

### ISSUE THREAD

**Issue by zssnode** [tension/NeWorld-For-WHMCS#1]
cart.php?a=confproduct&i=1:402 Uncaught ReferenceError: addtocart is not defined
    at HTMLButtonElement.onclick (cart.php?a=confproduct&i=1:402)

this line error:<button type="button" id="btnCompleteProductConfig" class="btn btn-success btn-check" onclick="addtocart()">

**Comment by tension** [comment]
Version 7.2 has not updated the theme
