### ISSUE TITLE
您好 购物车有问题（BUG）

### ISSUE THREAD

**Issue by ghost** [tension/NeWorld-For-WHMCS#2]
如果后台产品启用自定义字段 购物车就无法“继续”下一步 点击无反应

**Comment by miaovpn** [comment]
一样的问题，orderforms选其他模板就可以下一步
能修复吗？

**Comment by tension** [comment]
请查看 F12 报什么错！

**Comment by miaovpn** [comment]
![2017-07-18_235501](https://user-images.githubusercontent.com/28225813/28326933-aafc509e-6c14-11e7-9615-374d8bbcf140.png)
报错信息，谢谢
