### ISSUE TITLE
您好，WHMCS7.2.3购物车存在问题

### ISSUE THREAD

**Issue by hans362** [tension/NeWorld-For-WHMCS#3]
结账时出现付款方式但无法选择，且下面同意服务条款无勾选框。
图片：[http://ww2.sinaimg.cn/large/0060lm7Tly1fkuv5isgl8j30h40jxgml.jpg](url)

**Comment by avamiao** [comment]
老问题了
自己 F12
服务条款我也解决不了
把那个勾选框直接拿掉- -
这主题bug超多

**Comment by tension** [comment]
本来就是6.3.1 的时候发出来的 仅支持到 7.1.2 你们都用7.2.3 来测试 怎么玩？
